version: 2.1

orbs:
  pypi: pennlabs/pypi-tools@0.0.3

jobs:
  test:  # required for runs that don't use workflows
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          command: pip install -r dev-requirements.txt
      - run:
          command: make coverage
      - run:
          name: Upload coverage to codecov
          command: codecov -t 0a652abc-deea-4a9b-a31f-e0c564f121e1
  publish:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          command: make publish

workflows:
  version: 2.1
  build:
    jobs:
      - test
      - pypi/publish:
          requires:
            - test
          filters:
            branches:
              only: master
