version: 2

jobs:
  build:  # required for runs that don't use workflows
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          command: pip install -r dev-requirements.txt
      - run:
          command: make test
      - run:
          name: Upload coverage to codecov
          command: codecov -t 0a652abc-deea-4a9b-a31f-e0c564f121e1 -s /tmp/test-reports/coverage

