from typing import Dict

class RipgrepError(Exception): ...

def camel_to_snake(name: str) -> str: ...
def get_service_registry_code(class_module_map: Dict[str, str]) -> str: ...
def get_class_module_map() -> Dict[str, str]: ...
